---
apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
  name: kubernaut-ingress
  annotations:
    kubernetes.io/ingress.class: voyager
    ingress.appscode.com/type: LoadBalancer
    ingress.appscode.com/replicas: '2'
    ingress.appscode.com/stats: 'true'
spec:
  backend:
    serviceName: kubernaut
    servicePort: '80'

---
apiVersion: v1
kind: Service
metadata:
  name: kubernaut
spec:
  selector:
    app: kubernaut
  ports:
    - port: 80
      targetPort: web
      protocol: TCP

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kubernaut
  labels:
    app: kubernaut
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernaut
  template:
    metadata:
      labels:
        app: kubernaut
    spec:
      containers:
      - name: kubernaut
        image: {{image}}
        ports:
        - containerPort: 3001
          name: web
        volumeMounts:
        - name: kubectl-config
          mountPath: "/config/.kube"
          readOnly: true
      volumes:
        - name: kubectl-config
          secret:
            secretName: kubectl
