---
apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
  name: "{{service}}-ingress"
  annotations:
    kubernetes.io/ingress.class: voyager
    ingress.appscode.com/type: LoadBalancer
    ingress.appscode.com/replicas: '2'
    ingress.appscode.com/stats: 'true'
spec:
  backend:
    serviceName: {{service}}
    servicePort: '80'

---
apiVersion: v1
kind: Service
metadata:
  name: {{service}}
spec:
  selector:
    app: {{service}}
  ports:
    - port: 80
      targetPort: web
      protocol: TCP

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{service}}
  labels:
    app: {{service}}
    version: "{{version}}"
spec:
  replicas: {{replicas}}
  selector:
    matchLabels:
      app: {{service}}
  template:
    metadata:
      labels:
        app: {{service}}
    spec:
      containers:
      - name: {{service}}
        image: {{image}}
        ports:
        - containerPort: {{containerPort}}
          name: web
        env:
        - name: APP_ENV
          value: live
        - name: APP_NAME
          value: "{{service}}"
        - name: APP_VERSION
          value: "{{version}}"
        volumeMounts:
        - name: kubectl-config
          mountPath: "/config/.kube"
          readOnly: true
        - name: "{{service}}-config"
          mountPath: "/opt/{{service}}/secrets"
          readOnly: true
      volumes:
        - name: kubectl-config
          secret:
            secretName: kubectl
        - name: "{{service}}-config"
          secret:
            secretName: {{service}}
