---
apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
  name: kubernaut-ingress
  annotations:
    kubernetes.io/ingress.class: voyager
    ingress.appscode.com/type: LoadBalancer
    ingress.appscode.com/replicas: '2'
    ingress.appscode.com/stats: 'true'
spec:
  backend:
    serviceName: kubernaut
    servicePort: '80'

---
apiVersion: v1
kind: Service
metadata:
  name: {{service}}
spec:
  selector:
    app: {{service}}
  ports:
    - port: 80
      targetPort: web
      protocol: TCP

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{service}}
  labels:
    app: {{service}}
    version: {{version}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{service}}
  template:
    metadata:
      labels:
        app: {{service}}
    spec:
      containers:
      - name: {{service}}
        image: {{image}}
        ports:
        - containerPort: 3000
          name: web
        env:
        - name: APP_ENV
          value: live
        volumeMounts:
        - name: kubectl-config
          mountPath: "/config/.kube"
          readOnly: true
      volumes:
        - name: kubectl-config
          secret:
            secretName: kubectl
